package AgentCommand

type AgentCommand string

const (

	ADD_RABBITMQ_CLUSTER_DEPLOYMENT =AgentCommand("ADD_RABBITMQ_CLUSTER_DEPLOYMENT")
	REMOVE_RABBITMQ_CLUSTER_DEPLOYMENT=AgentCommand("REMOVE_RABBITMQ_CLUSTER_DEPLOYMENT")

	ADD_KAFKA_CLUSTER_DEPLOYMENT =AgentCommand("ADD_KAFKA_CLUSTER_DEPLOYMENT")
	ADD_KAFKA_MANAGER_DEPLOYMENT=AgentCommand("ADD_KAFKA_MANAGER_DEPLOYMENT")
)

var IsAgentCommand = map[string]bool{
	"ADD_RABBITMQ_CLUSTER_DEPLOYMENT": true,
	"REMOVE_RABBITMQ_CLUSTER_DEPLOYMENT": true,

	"ADD_KAFKA_CLUSTER_DEPLOYMENT":true,
	"ADD_KAFKA_MANAGER_DEPLOYMENT":true,
}

var GetAgentCommandString = map[AgentCommand]string{
	ADD_RABBITMQ_CLUSTER_DEPLOYMENT: "ADD_RABBITMQ_CLUSTER_DEPLOYMENT",
	REMOVE_RABBITMQ_CLUSTER_DEPLOYMENT: "REMOVE_RABBITMQ_CLUSTER_DEPLOYMENT",
	ADD_KAFKA_CLUSTER_DEPLOYMENT: "ADD_KAFKA_CLUSTER_DEPLOYMENT",
	ADD_KAFKA_MANAGER_DEPLOYMENT:"ADD_KAFKA_MANAGER_DEPLOYMENT",
}

var GetAgentCommandEnum = map[string]AgentCommand{
	"ADD_RABBITMQ_CLUSTER_DEPLOYMENT": ADD_RABBITMQ_CLUSTER_DEPLOYMENT,
	"REMOVE_RABBITMQ_CLUSTER_DEPLOYMENT": REMOVE_RABBITMQ_CLUSTER_DEPLOYMENT,
	"ADD_KAFKA_CLUSTER_DEPLOYMENT": ADD_KAFKA_CLUSTER_DEPLOYMENT,
}
